package fi.csc.avaa.paituli.db.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import fi.csc.avaa.paituli.db.model.paituliloki;
import fi.csc.avaa.paituli.db.service.paitulilokiLocalServiceUtil;

/**
 * The extended model base implementation for the paituliloki service. Represents a row in the &quot;loki&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link paitulilokiImpl}.
 * </p>
 *
 * @author pj
 * @see paitulilokiImpl
 * @see fi.csc.avaa.paituli.db.model.paituliloki
 * @generated
 */
public abstract class paitulilokiBaseImpl extends paitulilokiModelImpl
    implements paituliloki {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a paituliloki model instance should use the {@link paituliloki} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            paitulilokiLocalServiceUtil.addpaituliloki(this);
        } else {
            paitulilokiLocalServiceUtil.updatepaituliloki(this);
        }
    }
}
