package fi.csc.avaa.paituli.db.model;

import java.io.Serializable;
import java.util.Date;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portlet.expando.model.ExpandoBridge;

/**
 * The base model interface for the paituliloki service. Represents a row in the &quot;loki&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link fi.csc.avaa.paituli.db.model.impl.paitulilokiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link fi.csc.avaa.paituli.db.model.impl.paitulilokiImpl}.
 * </p>
 *
 * @author pj
 * @see paituliloki
 * @see fi.csc.avaa.paituli.db.model.impl.paitulilokiImpl
 * @see fi.csc.avaa.paituli.db.model.impl.paitulilokiModelImpl
 * @generated
 */
public interface paitulilokiModel extends BaseModel<paituliloki> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a paituliloki model instance should use the {@link paituliloki} interface instead.
     */

    /**
     * Returns the primary key of this paituliloki.
     *
     * @return the primary key of this paituliloki
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this paituliloki.
     *
     * @param primaryKey the primary key of this paituliloki
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the event_id of this paituliloki.
     *
     * @return the event_id of this paituliloki
     */
    public int getEvent_id();

    /**
     * Sets the event_id of this paituliloki.
     *
     * @param event_id the event_id of this paituliloki
     */
    public void setEvent_id(int event_id);

    /**
     * Returns the saltedhash of this paituliloki.
     *
     * @return the saltedhash of this paituliloki
     */
    @AutoEscape
    public String getSaltedhash();

    /**
     * Sets the saltedhash of this paituliloki.
     *
     * @param saltedhash the saltedhash of this paituliloki
     */
    public void setSaltedhash(String saltedhash);

    /**
     * Returns the organisaatio of this paituliloki.
     *
     * @return the organisaatio of this paituliloki
     */
    @AutoEscape
    public String getOrganisaatio();

    /**
     * Sets the organisaatio of this paituliloki.
     *
     * @param organisaatio the organisaatio of this paituliloki
     */
    public void setOrganisaatio(String organisaatio);

    /**
     * Returns the aineisto of this paituliloki.
     *
     * @return the aineisto of this paituliloki
     */
    @AutoEscape
    public String getAineisto();

    /**
     * Sets the aineisto of this paituliloki.
     *
     * @param aineisto the aineisto of this paituliloki
     */
    public void setAineisto(String aineisto);

    /**
     * Returns the tiedotojenlkm of this paituliloki.
     *
     * @return the tiedotojenlkm of this paituliloki
     */
    public int getTiedotojenlkm();

    /**
     * Sets the tiedotojenlkm of this paituliloki.
     *
     * @param tiedotojenlkm the tiedotojenlkm of this paituliloki
     */
    public void setTiedotojenlkm(int tiedotojenlkm);

    /**
     * Returns the paiva of this paituliloki.
     *
     * @return the paiva of this paituliloki
     */
    public Date getPaiva();

    /**
     * Sets the paiva of this paituliloki.
     *
     * @param paiva the paiva of this paituliloki
     */
    public void setPaiva(Date paiva);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(fi.csc.avaa.paituli.db.model.paituliloki paituliloki);

    @Override
    public int hashCode();

    @Override
    public CacheModel<fi.csc.avaa.paituli.db.model.paituliloki> toCacheModel();

    @Override
    public fi.csc.avaa.paituli.db.model.paituliloki toEscapedModel();

    @Override
    public fi.csc.avaa.paituli.db.model.paituliloki toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
